using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CFBpredictor
{
    public class NCAA
    {
        public List<Team> FBS = new List<Team>();
        public List<Team> FCS = new List<Team>();
        public List<Conference> DivisionI = new List<Conference>();

        public Team AirForce = new Team("Air Force", "MWC", "87");
        public Team Akron = new Team("Akron", "MAC", "47");
        public Team Alabama = new Team("Alabama", "SEC", "73");
        public Team AppalachianState = new Team("Appalachian State", "Sun Belt", "171");
        public Team Arizona = new Team("Arizona", "Pac 12", "57");
        public Team ArizonaState = new Team("Arizona State", "Pac 12", "58");
        public Team Arkansas = new Team("Arkansas", "SEC", "74");
        public Team ArkansasState = new Team("Arkansas State", "Sun Belt", "37");
        public Team Army = new Team("Army", "Independent", "97");
        public Team Auburn = new Team("Auburn", "SEC", "75");
        public Team BallState = new Team("Ball State", "MAC", "48");
        public Team Baylor = new Team("Baylor", "Big 12", "79");
        public Team BoiseState = new Team("Boise State", "MWC", "112");
        public Team BostonCollege = new Team("Boston College", "ACC", "10");
        public Team BowlingGreen = new Team("Bowling Green", "MAC", "49");
        public Team Buffalo = new Team("Buffalo", "MAC", "208");
        public Team BYU = new Team("BYU", "Independent", "88");
        public Team California = new Team("California", "Pac 12", "59");
        public Team CentralMichigan = new Team("Central Michigan", "MAC", "50");
        public Team Charlotte = new Team("Charlotte", "CUSA", "2595");
        public Team Cincinnati = new Team("Cincinnati", "AAC", "98");
        public Team Clemson = new Team("Clemson", "ACC", "1");
        public Team Colorado = new Team("Colorado", "Pac 12", "18");
        public Team ColoradoState = new Team("Colorado State", "MWC", "89");
        public Team Connecticut = new Team("Connecticut", "AAC", "202");
        public Team Duke = new Team("Duke", "ACC", "2");
        public Team EastCarolina = new Team("East Carolina", "AAC", "99");
        public Team EasternMichigan = new Team("Eastern Michigan", "MAC", "51");
        public Team Florida = new Team("Florida", "SEC", "67");
        public Team FloridaAtlantic = new Team("Florida Atlantic", "CUSA", "2294");
        public Team FloridaInternational = new Team("Florida International", "CUSA", "2307");
        public Team FloridaState = new Team("Florida State", "ACC", "3");
        public Team FresnoState = new Team("Fresno State", "MWC", "90");
        public Team Georgia = new Team("Georgia", "SEC", "68");
        public Team GeorgiaSouthern = new Team("Georgia Southern", "Sun Belt", "175");
        public Team GeorgiaState = new Team("Georgia State", "Sun Belt", "2558");
        public Team GeorgiaTech = new Team("Georgia Tech", "ACC", "4");
        public Team Hawaii = new Team("Hawaii", "MWC", "91");
        public Team Houston = new Team("Houston", "AAC", "80");
        public Team Idaho = new Team("Idaho", "Sun Belt", "114");
        public Team Illinois = new Team("Illinois", "Big Ten", "26");
        public Team Indiana = new Team("Indiana", "Big Ten", "27");
        public Team Iowa = new Team("Iowa", "Big Ten", "28");
        public Team IowaState = new Team("Iowa State", "Big 12", "19");
        public Team Kansas = new Team("Kansas", "Big 12", "20");
        public Team KansasState = new Team("Kansas State", "Big 12", "21");
        public Team KentState = new Team("Kent State", "MAC", "52");
        public Team Kentucky = new Team("Kentucky", "SEC", "69");
        public Team LouisianaTech = new Team("Louisiana Tech", "CUSA", "38");
        public Team LouisianaLafayette = new Team("Louisiana Lafayette", "Sun Belt", "45");
        public Team LouisianaMonroe = new Team("Louisiana Monroe", "Sun Belt", "103");
        public Team Louisville = new Team("Louisville", "ACC", "100");
        public Team LSU = new Team("LSU", "SEC", "76");
        public Team Marshall = new Team("Marshall", "CUSA", "176");
        public Team Maryland = new Team("Maryland", "Big Ten", "5");
        public Team Memphis = new Team("Memphis", "AAC", "101");
        public Team MiamiFl = new Team("Miami(FL)", "ACC", "11");
        public Team MiamiOh = new Team("Miami(OH)", "MAC", "53");
        public Team Michigan = new Team("Michigan", "Big Ten", "29");
        public Team MichiganState = new Team("Michigan State", "Big Ten", "30");
        public Team MiddleTennesseeState = new Team("Middle Tennessee State", "CUSA", "152");
        public Team Minnesota = new Team("Minnesota", "Big Ten", "31");
        public Team MississippiState = new Team("Mississippi State", "SEC", "78");
        public Team Missouri = new Team("Missouri", "SEC", "22");
        public Team Navy = new Team("Navy", "Independent", "102");
        public Team Nebraska = new Team("Nebraska", "Big Ten", "23");
        public Team Nevada = new Team("Nevada", "MWC", "39");
        public Team NewMexico = new Team("New Mexico", "MWC", "92");
        public Team NewMexicoState = new Team("New Mexico State", "Sun Belt", "41");
        public Team NorthCarolina = new Team("North Carolina", "ACC", "6");
        public Team NCState = new Team("NC State", "ACC", "7");
        public Team NorthTexas = new Team("North Texas", "CUSA", "182");
        public Team NorthernIllinois = new Team("Northern Illinois", "MAC", "42");
        public Team Northwestern = new Team("Northwestern", "Big Ten", "32");
        public Team NotreDame = new Team("Notre Dame", "Independent", "104");
        public Team Ohio = new Team("Ohio", "MAC", "54");
        public Team OhioState = new Team("Ohio State", "Big Ten", "33");
        public Team Oklahoma = new Team("Oklahoma", "Big 12", "24");
        public Team OklahomaState = new Team("Oklahoma State", "Big 12", "25");
        public Team OldDominion = new Team("Old Dominion", "CUSA", "2371");
        public Team OleMiss = new Team("Ole Miss", "SEC", "77");
        public Team Oregon = new Team("Oregon", "Pac 12", "60");
        public Team OregonState = new Team("Oregon State", "Pac 12", "61");
        public Team PennState = new Team("Penn State", "Big Ten", "34");
        public Team Pittsburgh = new Team("Pittsburgh", "ACC", "12");
        public Team Purdue = new Team("Purdue", "Big Ten", "35");
        public Team Rice = new Team("Rice", "CUSA", "81");
        public Team Rutgers = new Team("Rutgers", "Big Ten", "13");
        public Team SanDiegoState = new Team("San Diego State", "MWC", "93");
        public Team SanJoseState = new Team("San Jose State", "MWC", "44");
        public Team SMU = new Team("SMU", "AAC", "82");
        public Team SouthAlabama = new Team("South Alabama", "South Alabama", "2549");
        public Team SouthCarolina = new Team("South Carolina", "SEC", "70");
        public Team SouthFlorida = new Team("South Florida", "AAC", "1019");
        public Team SouthernMiss = new Team("Southern Miss", "CUSA", "105");
        public Team Stanford = new Team("Stanford", "Pac 12", "63");
        public Team Syracuse = new Team("Syracuse", "ACC", "14");
        public Team TCU = new Team("TCU", "Big 12", "85");
        public Team Temple = new Team("Temple", "AAC", "15");
        public Team Tennessee = new Team("Tennessee", "SEC", "71");
        public Team Texas = new Team("Texas", "Big 12", "83");
        public Team TexasAM = new Team("Texas A&M", "SEC", "84");
        public Team TexasState = new Team("Texas State", "Sun Belt", "185");
        public Team TexasTech = new Team("Texas Tech", "Big 12", "86");
        public Team Toledo = new Team("Toledo", "MAC", "55");
        public Team Troy = new Team("Troy", "Sun Belt", "222");
        public Team Tulane = new Team("Tulane", "AAC", "106");
        public Team Tulsa = new Team("Tulsa", "AAC", "107");
        public Team UAB = new Team("UAB", "CUSA");
        public Team UCF = new Team("Central Florida", "AAC", "210");
        public Team UCLA = new Team("UCLA", "Pac 12", "64");
        public Team UMass = new Team("UMass", "MAC", "204");
        public Team UNLV = new Team("UNLV", "MWC", "40");
        public Team USC = new Team("USC", "Pac 12", "62");
        public Team Utah = new Team("Utah", "Pac 12", "94");
        public Team UtahState = new Team("Utah State", "MWC", "46");
        public Team UTEP = new Team("UTEP", "CUSA", "95");
        public Team UTSA = new Team("UTSA", "CUSA", "2560");
        public Team Vanderbilt = new Team("Vanderbilt", "SEC", "72");
        public Team Virginia = new Team("Virginia", "ACC", "8");
        public Team VirginiaTech = new Team("Virginia Tech", "ACC", "16");
        public Team WakeForest = new Team("Wake Forest", "ACC", "9");
        public Team Washington = new Team("Washington", "Pac 12", "65");
        public Team WashingtonState = new Team("Washington State", "Pac 12", "66");
        public Team WestVirgnia = new Team("West Virginia", "Big 12", "17");
        public Team WesternKentucky = new Team("Western Kentucky", "CUSA", "224");
        public Team WesternMichigan = new Team("Western Michigan", "MAC", "56");
        public Team Wisconsin = new Team("Wisconsin", "Big Ten", "36");
        public Team Wyoming = new Team("Wyoming", "MWC", "96");
        public Conference AAC = new Conference("AAC");
        public Conference ACC = new Conference("ACC");
        public Conference Big12 = new Conference("Big 12");
        public Conference BigTen = new Conference("Big Ten");
        public Conference CUSA = new Conference("CUSA");
        public Conference independent = new Conference("Independent");
        public Conference MAC = new Conference("MAC");
        public Conference MWC = new Conference("MWC");
        public Conference Pac12 = new Conference("Pac 12");
        public Conference SEC = new Conference("SEC");
        public Conference SunBelt = new Conference("Sun Belt");

        //FCS Teams
        Team AbileneChr = new Team("Abilene Christian", "FCS", "276");
        Team AlabamaAM = new Team("Alabama A&M", "FCS", "356");
        Team AlabamaSt = new Team("Alabama State", "FCS", "187");
        Team Albany = new Team("Albany", "FCS", "546");
        Team AlcornSt = new Team("Alcorn State", "FCS", "188");
        Team ArkansasPB = new Team("Arkansas Pine Bluff", "FCS", "589");
        Team AustinPeay = new Team("Austin Peay", "FCS", "150");
        Team BethCook = new Team("Bethune Cookman", "FCS", "143");
        Team Brown = new Team("Brown", "FCS", "127");
        Team Bryant = new Team("Bryant", "FCS", "1948");
        Team Bucknell = new Team("Bucknell", "FCS", "159");
        Team Butler = new Team("Butler", "FCS", "165");
        Team CalPoly = new Team("Cal Poly", "FCS", "108");
        Team Campbell = new Team("Campbell", "FCS", "2357");
        Team CentArk = new Team("Central Arkansas", "FCS", "268");
        Team CentConn = new Team("Central Connecticut", "FCS", "209");
        Team CharlestonSo = new Team("Charleston Southern", "FCS", "211");
        Team Chattanooga = new Team("Chattanooga", "FCS", "177");
        Team Citadel = new Team("The Citadel", "FCS", "172");
        Team CoastalCar = new Team("Coastal Carolina", "FCS", "2316");
        Team Colgate = new Team("Colgate", "FCS", "160");
        Team Columbia = new Team("Columbia", "FCS", "128");
        Team Cornell = new Team("Cornell", "FCS", "129");
        Team Dartmouth = new Team("Dartmouth", "FCS", "130");
        Team Davidson = new Team("Davidson", "FCS", "212");
        Team Dayton = new Team("Dayton", "FCS", "166");
        Team Delaware = new Team("Delaware", "FCS", "195");
        Team DelawareSt = new Team("Delaware State", "FCS", "144");
        Team Drake = new Team("Drake", "FCS", "167");
        Team Duquesne = new Team("Duquesne", "FCS", "136");
        Team EastTennSt = new Team("East Tennessee State", "FCS", "173");
        Team EasternIll = new Team("Eastern Illinois", "FCS", "120");
        Team EasternKent = new Team("Eastern Kentucky", "FCS", "151");
        Team EasternWash = new Team("Eastern Washington", "FCS", "113");
        Team Elon = new Team("Elon", "FCS", "350");
        Team FloridaAM = new Team("Florida A&M", "FCS", "145");
        Team Fordham = new Team("Fordham", "FCS", "161");
        Team Furman = new Team("Furman", "FCS", "174");
        Team GardnerWebb = new Team("Gardner Webb", "FCS", "351");
        Team Georgetown = new Team("Georgetown", "FCS", "137");
        Team GramblingSt = new Team("Grambling State", "FCS", "189");
        Team Hampton = new Team("Hampton", "FCS", "229");
        Team Harvard = new Team("Harvard", "FCS", "131");
        Team HolyCross = new Team("Holy Cross", "FCS", "162");
        Team HoustonBaptist = new Team("Houston Baptist", "FCS", "2601");
        Team Howard = new Team("Howard", "FCS", "146");
        Team IdahoSt = new Team("Idaho State", "FCS", "115");
        Team IllinoisSt = new Team("Illinois State", "FCS", "121");
        Team IncarnateWord = new Team("Incarnate Word", "FCS", "2539");
        Team IndianaSt = new Team("Indiana State", "FCS", "122");
        Team JacksonState = new Team("Jackson State", "FCS", "190");
        Team Jacksonville = new Team("Jacksonville", "FCS", "2001");
        Team JacksonvilleSt = new Team("Jacksonville State", "FCS", "247");
        Team JamesMadison = new Team("James Madison", "FCS", "196");
        Team KennesawSt = new Team("Kennesaw State", "FCS", "2610");
        Team Lafayette = new Team("Lafayette", "FCS", "163");
        Team Lamar = new Team("Lamar", "FCS", "2559");
        Team Lehigh = new Team("Lehigh", "FCS", "164");
        Team Liberty = new Team("Liberty", "FCS", "215");
        Team Maine = new Team("Maine", "FCS", "203");
        Team Marist = new Team("Marist", "FCS", "139");
        Team McNeeseSt = new Team("McNeese State", "FCS", "180");
        Team Mercer = new Team("Mercer", "FCS", "2597");
        Team MissVallSt = new Team("Mississippi Valley State", "FCS", "191");
        Team MissouriSt = new Team("Missouri State", "FCS", "125");
        Team Monmouth = new Team("Monmouth", "FCS", "216");
        Team Montana = new Team("Montana", "FCS", "116");
        Team MontanaState = new Team("Montana State", "FCS", "117");
        Team MoreheadSt = new Team("Morehead State", "FCS", "153");
        Team MorganSt = new Team("Morgan State", "FCS", "147");
        Team MurrayState = new Team("Murray State", "FCS", "154");
        Team NewHamphshire = new Team("New Hampshire", "FCS", "205");
        Team NichollsSt = new Team("Nicholls State", "FCS", "181");
        Team NorfolkSt = new Team("Norfolk State", "FCS", "233");
        Team NorthCarAT = new Team("North Carolina A&T", "FCS", "148");
        Team NCCentral = new Team("NC Central", "FCS", "621");
        Team NorthDakota = new Team("North Dakota", "FCS", "308");
        Team NorthDakotaSt = new Team("North Dakota State", "FCS", "309");
        Team NorthernArizona = new Team("Northern Arizona", "FCS", "118");
        Team NorthernColorado = new Team("Northern Colorado", "FCS", "310");
        Team NorthernIowa = new Team("Northern Iowa", "FCS", "123");
        Team NorthwesternSt = new Team("Northwestern State", "FCS", "183");
        Team Penn = new Team("Penn", "FCS", "132");
        Team PortlandSt = new Team("Portland State", "FCS", "257");
        Team PrairieViewAM = new Team("Prairie View A&M", "FCS", "192");
        Team Presbyterian = new Team("Presbyterian", "FCS", "354");
        Team Princeton = new Team("Princeton", "FCS", "133");
        Team RhodeIsland = new Team("Rhode Island", "FCS", "206");
        Team Richmond = new Team("Richmond", "FCS", "198");
        Team RobertMorris = new Team("Robert Morris", "FCS", "217");
        Team SacramentoSt = new Team("Sacramento State", "FCS", "110");
        Team SacredHeart = new Team("Sacred Heart", "FCS", "259");
        Team StFrancis = new Team("Saint Francis", "FCS", "219");
        Team SamHoustonSt = new Team("Sam Houston State", "FCS", "184");
        Team Samford = new Team("Samford", "FCS", "218");
        Team SanDiego = new Team("San Diego", "FCS", "169");
        Team SavannahSt = new Team("Savannah State", "FCS", "363");
        Team SCState = new Team("South Carolina State", "FCS", "149");
        Team SouthDakota = new Team("South Dakota", "FCS", "311");
        Team SouthDakotaSt = new Team("South Dakota State", "FCS", "312");
        Team SEMOSt = new Team("Southeast Missouri State", "FCS", "155");
        Team SoutheastLa = new Team("Southeastern Louisiana", "FCS", "2234");
        Team Southern = new Team("Southern", "FCS", "193");
        Team SouthernIll = new Team("Southern Illinois", "FCS", "124");
        Team SouthernUtah = new Team("Southern Utah", "FCS", "111");
        Team StephenFAustin = new Team("Stephen F. Austin", "FCS", "186");
        Team Stetson = new Team("Stetson", "FCS", "2598");
        Team StonyBrook = new Team("Stony Brook", "FCS", "629");
        Team TennesseeSt = new Team("Tennessee State", "FCS", "157");
        Team TennesseeTech = new Team("Tennessee Tech", "FCS", "158");
        Team TexasSouthern = new Team("Texas Southern", "FCS", "194");
        Team Towson = new Team("Towson", "FCS", "221");
        Team UCDavis = new Team("UC Davis", "FCS", "263");
        Team TennMartin = new Team("Tennessee Martin", "FCS", "156");
        Team Valparaiso = new Team("Valparaiso", "FCS", "170");
        Team Villanova = new Team("Villanova", "FCS", "199");
        Team VMI = new Team("Virginia Military", "FCS", "178");
        Team Wagner = new Team("Wagner", "FCS", "223");
        Team WeberState = new Team("Weber State", "FCS", "119");
        Team WCarolina = new Team("Western Carolina", "FCS", "179");
        Team WesternIll = new Team("Western Illinois", "FCS", "126");
        Team WilliamMary = new Team("William & Mary", "FCS", "200");
        Team Wofford = new Team("Wofford", "FCS", "267");
        Team Yale = new Team("Yale", "FCS", "134");
        Team YoungstownSt = new Team("Youngstown State", "FCS", "225");
        Conference AA = new Conference("FCS");

        public NCAA()
        {
            FBS.Add(AirForce);
            FBS.Add(Akron);
            FBS.Add(Alabama);
            FBS.Add(AppalachianState);
            FBS.Add(Arizona);
            FBS.Add(ArizonaState);
            FBS.Add(Arkansas);
            FBS.Add(ArkansasState);
            FBS.Add(Army);
            FBS.Add(Auburn);
            FBS.Add(BallState);
            FBS.Add(Baylor);
            FBS.Add(BoiseState);
            FBS.Add(BostonCollege);
            FBS.Add(BowlingGreen);
            FBS.Add(Buffalo);
            FBS.Add(BYU);
            FBS.Add(California);
            FBS.Add(CentralMichigan);
            FBS.Add(Charlotte);
            FBS.Add(Cincinnati);
            FBS.Add(Clemson);
            FBS.Add(Colorado);
            FBS.Add(ColoradoState);
            FBS.Add(Connecticut);
            FBS.Add(Duke);
            FBS.Add(EastCarolina);
            FBS.Add(EasternMichigan);
            FBS.Add(Florida);
            FBS.Add(FloridaAtlantic);
            FBS.Add(FloridaInternational);
            FBS.Add(FloridaState);
            FBS.Add(FresnoState);
            FBS.Add(Georgia);
            FBS.Add(GeorgiaSouthern);
            FBS.Add(GeorgiaState);
            FBS.Add(GeorgiaTech);
            FBS.Add(Hawaii);
            FBS.Add(Houston);
            FBS.Add(Idaho);
            FBS.Add(Illinois);
            FBS.Add(Indiana);
            FBS.Add(Iowa);
            FBS.Add(IowaState);
            FBS.Add(Kansas);
            FBS.Add(KansasState);
            FBS.Add(KentState);
            FBS.Add(Kentucky);
            FBS.Add(LouisianaTech);
            FBS.Add(LouisianaLafayette);
            FBS.Add(LouisianaMonroe);
            FBS.Add(Louisville);
            FBS.Add(LSU);
            FBS.Add(Marshall);
            FBS.Add(Maryland);
            FBS.Add(Memphis);
            FBS.Add(MiamiFl);
            FBS.Add(MiamiOh);
            FBS.Add(Michigan);
            FBS.Add(MichiganState);
            FBS.Add(MiddleTennesseeState);
            FBS.Add(Minnesota);
            FBS.Add(MississippiState);
            FBS.Add(Missouri);
            FBS.Add(Navy);
            FBS.Add(Nebraska);
            FBS.Add(Nevada);
            FBS.Add(NewMexico);
            FBS.Add(NewMexicoState);
            FBS.Add(NorthCarolina);
            FBS.Add(NCState);
            FBS.Add(NorthTexas);
            FBS.Add(NorthernIllinois);
            FBS.Add(Northwestern);
            FBS.Add(NotreDame);
            FBS.Add(Ohio);
            FBS.Add(OhioState);
            FBS.Add(Oklahoma);
            FBS.Add(OklahomaState);
            FBS.Add(OldDominion);
            FBS.Add(OleMiss);
            FBS.Add(Oregon);
            FBS.Add(OregonState);
            FBS.Add(PennState);
            FBS.Add(Pittsburgh);
            FBS.Add(Purdue);
            FBS.Add(Rice);
            FBS.Add(Rutgers);
            FBS.Add(SanDiegoState);
            FBS.Add(SanJoseState);
            FBS.Add(SMU);
            FBS.Add(SouthAlabama);
            FBS.Add(SouthCarolina);
            FBS.Add(SouthFlorida);
            FBS.Add(SouthernMiss);
            FBS.Add(Stanford);
            FBS.Add(Syracuse);
            FBS.Add(TCU);
            FBS.Add(Temple);
            FBS.Add(Tennessee);
            FBS.Add(Texas);
            FBS.Add(TexasAM);
            FBS.Add(TexasState);
            FBS.Add(TexasTech);
            FBS.Add(Toledo);
            FBS.Add(Troy);
            FBS.Add(Tulane);
            FBS.Add(Tulsa);
            //FBS.Add(UAB); UAB will start again in 2017
            FBS.Add(UCF);
            FBS.Add(UCLA);
            FBS.Add(UMass);
            FBS.Add(UNLV);
            FBS.Add(USC);
            FBS.Add(Utah);
            FBS.Add(UtahState);
            FBS.Add(UTEP);
            FBS.Add(UTSA);
            FBS.Add(Vanderbilt);
            FBS.Add(Virginia);
            FBS.Add(VirginiaTech);
            FBS.Add(WakeForest);
            FBS.Add(Washington);
            FBS.Add(WashingtonState);
            FBS.Add(WestVirgnia);
            FBS.Add(WesternKentucky);
            FBS.Add(WesternMichigan);
            FBS.Add(Wisconsin);
            FBS.Add(Wyoming);
            DivisionI.Add(AAC);
            DivisionI.Add(ACC);
            DivisionI.Add(Big12);
            DivisionI.Add(BigTen);
            DivisionI.Add(CUSA);
            DivisionI.Add(independent);
            DivisionI.Add(MAC);
            DivisionI.Add(MWC);
            DivisionI.Add(Pac12);
            DivisionI.Add(SEC);
            DivisionI.Add(SunBelt);

            FCS.Add(AbileneChr);
            FCS.Add(AlabamaAM);
            FCS.Add(AlabamaSt);
            FCS.Add(Albany);
            FCS.Add(AlcornSt);
            FCS.Add(ArkansasPB);
            FCS.Add(AustinPeay);
            FCS.Add(BethCook);
            FCS.Add(Brown);
            FCS.Add(Bryant);
            FCS.Add(Bucknell);
            FCS.Add(Butler);
            FCS.Add(CalPoly);
            FCS.Add(Campbell);
            FCS.Add(CentArk);
            FCS.Add(CentConn);
            FCS.Add(CharlestonSo);
            FCS.Add(Chattanooga);
            FCS.Add(Citadel);
            FCS.Add(CoastalCar);
            FCS.Add(Colgate);
            FCS.Add(Columbia);
            FCS.Add(Cornell);
            FCS.Add(Dartmouth);
            FCS.Add(Davidson);
            FCS.Add(Dayton);
            FCS.Add(Delaware);
            FCS.Add(DelawareSt);
            FCS.Add(Drake);
            FCS.Add(Duquesne);
            FCS.Add(EastTennSt);
            FCS.Add(EasternIll);
            FCS.Add(EasternKent);
            FCS.Add(EasternWash);
            FCS.Add(Elon);
            FCS.Add(FloridaAM);
            FCS.Add(Fordham);
            FCS.Add(Furman);
            FCS.Add(GardnerWebb);
            FCS.Add(Georgetown);
            FCS.Add(GramblingSt);
            FCS.Add(Hampton);
            FCS.Add(Harvard);
            FCS.Add(HolyCross);
            FCS.Add(HoustonBaptist);
            FCS.Add(Howard);
            FCS.Add(IdahoSt);
            FCS.Add(IllinoisSt);
            FCS.Add(IncarnateWord);
            FCS.Add(IndianaSt);
            FCS.Add(JacksonState);
            FCS.Add(Jacksonville);
            FCS.Add(JacksonvilleSt);
            FCS.Add(JamesMadison);
            FCS.Add(KennesawSt);
            FCS.Add(Lafayette);
            FCS.Add(Lamar);
            FCS.Add(Lehigh);
            FCS.Add(Liberty);
            FCS.Add(Maine);
            FCS.Add(Marist);
            FCS.Add(McNeeseSt);
            FCS.Add(Mercer);
            FCS.Add(MissVallSt);
            FCS.Add(MissouriSt);
            FCS.Add(Monmouth);
            FCS.Add(Montana);
            FCS.Add(MontanaState);
            FCS.Add(MoreheadSt);
            FCS.Add(MorganSt);
            FCS.Add(MurrayState);
            FCS.Add(NewHamphshire);
            FCS.Add(NichollsSt);
            FCS.Add(NorfolkSt);
            FCS.Add(NorthCarAT);
            FCS.Add(NCCentral);
            FCS.Add(NorthDakota);
            FCS.Add(NorthDakotaSt);
            FCS.Add(NorthernArizona);
            FCS.Add(NorthernColorado);
            FCS.Add(NorthernIowa);
            FCS.Add(NorthwesternSt);
            FCS.Add(Penn);
            FCS.Add(PortlandSt);
            FCS.Add(PrairieViewAM);
            FCS.Add(Presbyterian);
            FCS.Add(Princeton);
            FCS.Add(RhodeIsland);
            FCS.Add(Richmond);
            FCS.Add(RobertMorris);
            FCS.Add(SacramentoSt);
            FCS.Add(SacredHeart);
            FCS.Add(StFrancis);
            FCS.Add(SamHoustonSt);
            FCS.Add(Samford);
            FCS.Add(SanDiego);
            FCS.Add(SavannahSt);
            FCS.Add(SCState);
            FCS.Add(SouthDakota);
            FCS.Add(SouthDakotaSt);
            FCS.Add(SoutheastLa);
            FCS.Add(SEMOSt);
            FCS.Add(Southern);
            FCS.Add(SouthernIll);
            FCS.Add(SouthernUtah);
            FCS.Add(StephenFAustin);
            FCS.Add(Stetson);
            FCS.Add(StonyBrook);
            FCS.Add(TennesseeSt);
            FCS.Add(TennesseeTech);
            FCS.Add(TexasSouthern);
            FCS.Add(Towson);
            FCS.Add(UCDavis);
            FCS.Add(TennMartin);
            FCS.Add(Valparaiso);
            FCS.Add(Villanova);
            FCS.Add(VMI);
            FCS.Add(Wagner);
            FCS.Add(WeberState);
            FCS.Add(WCarolina);
            FCS.Add(WesternIll);
            FCS.Add(WilliamMary);
            FCS.Add(Wofford);
            FCS.Add(Yale);
            FCS.Add(YoungstownSt);

            DivisionI.Add(AA);
        }
    }
}
